### PR TITLE
Added support for Conditional substitution

### PR DESCRIPTION
**Pull request by LupusUmbrae**
This should fix issues #11

### CODE REVIEW

**Comment by dragos** [comment]
All right, thanks a lot! I'll merge it as soon as the CI passes.

**Comment by dragos** [comment]
It passed on my computer, the failure on Travis is related to memory. I'll merge and try to fix it later.

**Comment by mkurz** [comment]
A new release with this feature would be nice

**Comment by dragos** [comment]
Just pushed it. 1.0.4 is on Bintray

**Comment by Mossinarium** [comment]
Installed (Mars.2) and my errors are gone :) took a clean of the project to update them.

Thanks for the fast turn around @dragos

**Comment by dragos** [comment]
Thanks for your contribution!

**Pull request merged**
